### ISSUE TITLE
Doom Emacs fails to install

### ISSUE THREAD

**Issue by syphoxy** [nix-community/nix-doom-emacs#302] opened 2022-10-13 05:26 UTC
I'm honestly not sure what the problem is here but I'll provide as much information as possible such that the issue hopefully is self-describing.

`flake.nix`:
``` nix
{
  inputs = {
    nixpkgs.url =
      "github:NixOS/nixpkgs/nixos-22.05";

    home-manager.url =
      "github:nix-community/home-manager/release-22.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    emacs-overlay.url =
      "github:nix-community/emacs-overlay";
    emacs-overlay.flake = false;

    nix-doom-emacs.url =
      "github:nix-community/nix-doom-emacs";
    nix-doom-emacs.inputs.nixpkgs.follows = "nixpkgs";
    nix-doom-emacs.inputs.emacs-overlay.follows = "emacs-overlay";
  };

  outputs = inputs: let
    mkNixosConfigurations = builtins.mapAttrs (host: system:
      import ./${host} {
        inherit (inputs) nixpkgs home-manager;
        inherit inputs system;
      }
    );
  in {
    nixosConfigurations = mkNixosConfigurations {
      x = "x86_64-linux";
    };
  };
}
```

`x/default.nix`:
``` nix
{ nixpkgs, home-manager, inputs, system }:

nixpkgs.lib.nixosSystem {
  inherit system;

  modules = [
    home-manager.nixosModules.home-manager {
      home-manager = {
        useGlobalPkgs = true;
        useUserPackages = true;
        extraSpecialArgs = { inherit (inputs) nix-doom-emacs; };
        users.x = import ../home/x;
      };
    }
  ];
}
```

`../home/x/default.x`:
``` nix
{ pkgs, ... }:

{
  imports = [
    ./doom-emacs
  ];
}
```

`doom-emacs/default.nix`:
``` nix
{ pkgs, nix-doom-emacs, ... }:

{
  imports = [ nix-doom-emacs.hmModule ];

  programs.doom-emacs = {
    enable = true;
    doomPrivateDir = ./doom.d;

    emacsPackagesOverlay = self: super: with pkgs.emacsPackages; {
      gitignore-mode = git-modes;
      gitconfig-mode = git-modes;
    };
  };
}
```

Logs:

``` prompt
$ sudo nixos-rebuild switch         
building the system configuration...
error: builder for '/nix/store/4gwymw411ig955rl4jqc8fcgpz8xkhaa-straight-emacs-env.drv' failed with exit code 255;
       last 10 log lines:
       >       (apply #[257 "\306\307!\210\310\311\"A@\312!\313\314\315\313...
       >       (let (autoload-compute-prefixes) (apply fn args))
       >       (doom-cli--straight-no-compute-prefixes-a #[257 "\306\307!\210\310\3...
       >       (apply doom-cli--straight-no-compute-prefixes-a #[257 "\306\307!\210\3...
       >       (straight--build-autoloads (:local-repo "bind-key" :repo "bind-key" :t...
       >       (run-hook-with-args straight--build-autoloads (:local-repo "bind-key" ...
       >       (straight--build-package (:local-repo "bind-key" :repo "bind-key" :typ...
       > \310\304!\300\211\311>?\205\312!...
       >       (straight--transaction-exec use-package-\"0f26964d170469320dba0467483f...
       >     ! Wrote extended backtrace to /nix/store/z42pmjqplzhvsxdgrf9vsk9ffmzpxsrz-straight-emacs-env/logs/cli.doom.221013050934.176.error
       For full logs, run 'nix log /nix/store/4gwymw411ig955rl4jqc8fcgpz8xkhaa-straight-emacs-env.drv'.
error: 1 dependencies of derivation '/nix/store/28gy483r7278s4wa8xn0n42vmbs09cij-emacs-with-packages-28.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jfsa6524171jjlb5jw5hsvfnmh5xy4nk-emacs-with-packages-with-packages-28.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/s5fnkkk5ny7h25c6i8304c16l6x0ws5c-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ncjiiwm12zszzs68h5bmv0wlc5kib0kd-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/c54m6m6wdv73fxrdyvyr5zrvzwid95rd-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j0hbbqpvd4yjmhrl99sxy28m62pwyylb-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rngxnwpi03ns876f2sp0jnhbpzvq00kp-nixos-system-x-22.05.20221012.9234f5a.drv' failed to build
```

``` prompt
$ nix log /nix/store/4gwymw411ig955rl4jqc8fcgpz8xkhaa-straight-emacs-env.drv
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Loading /nix/store/fmwi35zh6jhcd80rq2dxnmd04k6cck85-doom-src/bin/doom...
Installing Doom Emacs!

- Skipping /nix/store/2d2c9f6xg64yqr0qrbf60yrm2gxarslq-doom.d/ (already exists)
  - Skipping init.el (already exists)
  - Skipping config.el (already exists)
  - Skipping packages.el (already exists)
Installing plugins
> Installing packages...
  - Checked out use-package: e2d173b1200865a9efd5c2066831a230497582c0
  > Building use-package...
  > Building use-package > Building bind-key...
  x There was an unexpected runtime error
    Message: Defining as dynamic an already lexical var
    Backtrace:
      (defvar autoload-compute-prefixes t ("/nix/store/3jdx3wfwnm78cv6vgj5fp...
      (require autoload)
      (#[257 "\306\307!\210\310^A\311\"A@\312^A!\313\314\315\313^X^Y^Z\3...
      (apply #[257 "\306\307!\210\310^A\311\"A@\312^A!\313\314\315\313^X^Y^Z...
      (let (autoload-compute-prefixes) (apply fn args))
      (doom-cli--straight-no-compute-prefixes-a #[257 "\306\307!\210\310^A\3...
      (apply doom-cli--straight-no-compute-prefixes-a #[257 "\306\307!\210\3...
      (straight--build-autoloads (:local-repo "bind-key" :repo "bind-key" :t...
      (run-hook-with-args straight--build-autoloads (:local-repo "bind-key" ...
      (straight--build-package (:local-repo "bind-key" :repo "bind-key" :typ...
      (#[0 "\307\305^N4\"\306?\206^M^@\310\304!\300\211\311>?\205^X^@\312^A!...
      (straight--transaction-exec use-package-\"0f26964d170469320dba0467483f...
    ! Wrote extended backtrace to /nix/store/z42pmjqplzhvsxdgrf9vsk9ffmzpxsrz-straight-emacs-env/logs/cli.doom.221013050934.176.error
```

`/nix/store/z42pmjqplzhvsxdgrf9vsk9ffmzpxsrz-straight-emacs-env/logs/cli.doom.221013050934.176.error` attached as [cli.doom.221013050934.176.error.log.gz](https://github.com/nix-community/nix-doom-emacs/files/9771026/cli.doom.221013050934.176.error.log.gz)

**Comment by Hajitorus** [comment] 2022-10-15 12:56
Locally, I've gotten emacs working again by pinning doomemacs to an old commit:

``` nix
{
    doom-emacs.url = "github:doomemacs/doomemacs/3853dff5e11655e858d0bfae64b70cb12ef685ac";
    doom-emacs.flake = false;
    nix-doom-emacs.inputs.doom-emacs.follows = "doom-emacs";
}
```

The first commit *after* this breaks compilation with missing "defcli!". The most recent commit (at time of writing, `9f22a0a2a5191cf57184846281164f478df4b7ac`) yields the above defvar error. I'm not sure if there are commits in the middle that would work, but if I have time this weekend I may try a more recent working commit.

**Comment by thiagokokada** [comment] 2022-10-15 16:29
> Locally, I've gotten emacs working again by pinning doomemacs to an old commit:
> 
> ```nix
> {
>     doom-emacs.url = "github:doomemacs/doomemacs/3853dff5e11655e858d0bfae64b70cb12ef685ac";
>     doom-emacs.flake = false;
>     nix-doom-emacs.inputs.doom-emacs.follows = "doom-emacs";
> }
> ```
> 
> The first commit _after_ this breaks compilation with missing "defcli!". The most recent commit (at time of writing, `9f22a0a2a5191cf57184846281164f478df4b7ac`) yields the above defvar error. I'm not sure if there are commits in the middle that would work, but if I have time this weekend I may try a more recent working commit.

You're really not supposed to set override doom-emacs because of #268. However, the commit that is pinned in this repository is supposed to work.

I still need to test to see if the issue is `emacs-overlay` update or something. But in general overriding inputs in nix-doom-emacs is a bad idea.

**Comment by thiagokokada** [comment] 2022-10-16 22:30
> Locally, I've gotten emacs working again by pinning doomemacs to an old commit:
> 
> ```nix
> {
>     doom-emacs.url = "github:doomemacs/doomemacs/3853dff5e11655e858d0bfae64b70cb12ef685ac";
>     doom-emacs.flake = false;
>     nix-doom-emacs.inputs.doom-emacs.follows = "doom-emacs";
> }
> ```
> 
> The first commit _after_ this breaks compilation with missing "defcli!". The most recent commit (at time of writing, `9f22a0a2a5191cf57184846281164f478df4b7ac`) yields the above defvar error. I'm not sure if there are commits in the middle that would work, but if I have time this weekend I may try a more recent working commit.

Anyway, since `3853dff5e11655e858d0bfae64b70cb12ef685ac` is newer than the current commit that we are pining, I am explicitly pining it in PR #308 until we have more time to investigate the issues.

**Comment by thiagokokada** [comment] 2022-10-25 21:05
With #319 merged this issue should be fixed. Please comment here otherwise and I will reopen the issue.

> This stopped happening here after I removed all the inputs' overrides.

Yeah, please remove any input override so we can use the tested pins instead.

**Closed by thiagokokada** 2022-10-25 21:05 UTC
Labels: bug
