### ISSUE TITLE
called with unexpected argument 'orgPackages' on the latest nixpkgs

### ISSUE THREAD

**Issue by cab404** [nix-community/nix-doom-emacs#53] opened 2022-02-10 04:38 UTC
while using home-manager module

```
error: anonymous function at /nix/store/xpifs2w4s1cwkvc68sp89rrg475zwq81-source/pkgs/top-level/emacs-packages.nix:58:53 called with unexpected argument 'orgPackages'

       at /nix/store/xpifs2w4s1cwkvc68sp89rrg475zwq81-source/lib/customisation.nix:69:16:

           68|     let
           69|       result = f origArgs;
             |                ^
           70|
(use '--show-trace' to show detailed location information)

```

meanwhile, nixpkgs:
    <para>
      <literal>pkgs.emacsPackages.orgPackages</literal> is removed
      because org elpa is deprecated. The packages in the top level
      of <literal>pkgs.emacsPackages</literal>, such as org and
      org-contrib, refer to the ones in
      <literal>pkgs.emacsPackages.elpaPackages</literal> and
      <literal>pkgs.emacsPackages.nongnuPackages</literal> where the
      new versions will release.
    </para>

**Comment by znewman01** [comment] 2022-02-12 16:49
See also https://github.com/vlaci/nix-doom-emacs/issues/401

**Comment by ckiee** [comment] 2022-02-13 02:01
Can I have your config to play with it myself? Or a reproducer?

**Comment by ckiee** [comment] 2022-02-15 02:52
Maybe the bug is that there is no bug.. At least in this repo.
```nix
    doom-emacs-nix = {
      url = "github:vlaci/nix-doom-emacs";
      
 ```

**Comment by znewman01** [comment] 2022-02-15 03:14
Ha, typo (I copied that from the other issue, not my config). I *did* experience this same issue with `doom-emacs.url = "github:nix-community/nix-doom-emacs";`.

**Comment by thiagokokada** [comment] 2022-09-12 20:05
Closing this since the issue seems to be fixed. Reply here if you want me to reopen it.

**Closed by thiagokokada** 2022-09-12 20:05 UTC
Labels: answer required
